spring:
  application:
    name: microservice-consumer-movie
server:
  port: 8095
user:
  userServicePath: http://localhost:8070/user/
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
logging:
  level:
    com.liu.cloud.movie.feign.UserFeignClient:  DEBUG