spring:
  application:
    name: microservice-consumer-movie-ribbon-without-eureka
server:
  port: 8094
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
    region:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
ribbon:
  eureka:
    enabled:  false
microservice-provider-user:
  ribbon:
    listOfServers:  localhost:8070